### ISSUE TITLE
Publish on lit

### ISSUE THREAD

**Issue by yagop** [cyrilis/luvit-mongodb#1]
The title explains it all.

https://luvit.io/lit.html
https://github.com/luvit/lit/wiki/Creating-Your-First-Package

**Comment by cyrilis** [comment]
Thanks, @yagop 
I've published to lit: https://luvit.io/lit.html#luvit-mongodb 
If you have any questions with this library, feel free to open issues. 
:smiley:

**Comment by yagop** [comment]
Thanks a lot @cyrilis 
Amazing work!

![http://i.imgur.com/Lumyr.gif](http://i.imgur.com/Lumyr.gif)

**Comment by cyrilis** [comment]
@yagop :sweat_smile:
