### ISSUE TITLE
插入文档的问题

### ISSUE THREAD

**Issue by reasonMix** [cyrilis/luvit-mongodb#3]
当插入一个文档里面包含 0,的时候，会插入一个非数字的值进去，比如 insert {a = 0}

**Comment by reasonMix** [comment]
bson.lua的197行 改为 if v ~= 0 and v * 2 == v then 就正确了

**Comment by cyrilis** [comment]
hi @reasonMix ,

非常感谢您的反馈，确实是有这样问题， 已经 fix. :smile:
