### ISSUE TITLE
插入问题

### ISSUE THREAD

**Issue by reasonMix** [cyrilis/luvit-mongodb#6]
一个循环一次插入50个文档，然后提示错误了。测试代码是
for i = 1,50 do
    local insert = {
      uid = math.floor(math.random(1000)),
      bean = math.floor(math.random(1000))
    }

    mongo:insert("Leaderboard", insert, nil, function(err, res)
      print('insert Leaderboard complete')
    end)

堆栈报错是
Uncaught Error: [string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:18: Unable to read enough characters
stack traceback:
	[C]: in function 'assert'
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:18: in function <[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:13>
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:68: in function 'parseMsgHeader'
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:233: in function '_onData'
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:247: in function '_onData'
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:247: in function '_onData'
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:247: in function '_onData'
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:247: in function '_onData'
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:247: in function '_onData'
	[string "/Users/liuyuntao/work/shengjiserver/deps/luvi..."]:247: in function '_onData'

**Comment by cyrilis** [comment]
Hi @reasonMix ,

好像是解析 header 的时候数据不完全导致的 bug, 现在已经更新并重新发布，你再试一下新版本(@v0.0.8)？

**Comment by reasonMix** [comment]
@cyrilis 刚测试了0.0.8，已经正常了。谢谢

**Comment by cyrilis** [comment]
@reasonMix   My pleasure. :smile:
