### ISSUE TITLE
排序的问题

### ISSUE THREAD

**Issue by reasonMix** [cyrilis/luvit-mongodb#7]
hi，我现在使用的是 $orderby来做的排序，但mongodb的文档上写的是 
Deprecated since version 3.2: The $orderby operator is deprecated. Use cursor.sort() instead.
我们使用的 mongodb是2.6，所以目前还能获取到排好序的数据，但是我看你们的 cursor 没有提供sort的操作。是不是有其他地方可以使用？

**Comment by cyrilis** [comment]
我前两天刚加上 sort 的方法，还没来得及更新文档和发布，但是实现也是用的  `$orderby`, 稍后会更新 sort 方法的实现， 但是接口应该不会变，你可以先用 `sort` 接口， 这里的接口文档是：

`cursor:sort(doc[, callback])`
- `doc`: **table**, 
- `callback`: optional, callback function

Example:
```lua
local User = db:collection("user")
User:find():sort({age = 1}):exec(function(err, res)
    p(err, res)
end)
```

**Comment by cyrilis** [comment]
@reasonMix  
已发布  cyrilis/luvit-mongodb/v0.0.10

**Comment by reasonMix** [comment]
@cyrilis 👌，我更新下

**Comment by reasonMix** [comment]
@cyrilis mongodb的c驱动，里面的cursor的实现，每次调用一次next就会发起网络调用然后获取下一条文档，这个是在协议层上实现吗？

**Comment by cyrilis** [comment]
@reasonMix  是的， 这个也是应该协议层实现，但是我还没加上。
