### ISSUE TITLE
负数读取的问题

### ISSUE THREAD

**Issue by reasonMix** [cyrilis/luvit-mongodb#8]
你好，目前遇到能正常插入一个负数，但是读取的时候，读出来的是一个无符号整数的问题

**Comment by reasonMix** [comment]
我改了下 bson.lua的177行 
v = le_int_to_num ( get ( 4 ) , 1 , 8 )->v = le_int_to_num ( get ( 4 ) , 1 , 4 )

utils.lua的
le_int_to_num函数的
if n > 2^overflow then-》
if n > 2^overflow then
  n = ( n % overflow ) - overflow

**Comment by cyrilis** [comment]
@reasonMix 赞， 果然是这样。我更新一下。

**Comment by cyrilis** [comment]
@reasonMix  已经更新，已发布， 版本号 `@v0.0.23`
